### ISSUE TITLE
Does sls invoke local work?

### ISSUE THREAD

**Issue by tomtomau** [justindra/townhub#17]
Hey mate

This is sick and i've been using it as a reference for one of our projects.

Have you gotten `sls invoke local` to work?

From what I can tell it probably doesn't work on this package as the serverless-rollup-plugin doesn't support it [as seen in this issue](https://github.com/drg-adaptive/serverless-rollup-plugin/issues/21)

It means serverless tries to find the javascript that's been transpiled from Typescript but without rollup (with the typescript plugin), it's not transpiling and loses its shit.

Hope you're well!

**Comment by justindra** [comment]
Good question! 

Doesn't look like it would. I haven't had to use it at this point, but will add it to the list to check out at some point.

**Comment by justindra** [comment]
@tomtomau sorry, completely forgot to test this. Yea it doesn't seem to work. Just have to keep an eye on that issue I guess or move to Webpack.
